FROM ubuntu:latest
    LABEL Author="Nilesh"
    
    USER root

    RUN apt install java-11-openjdk -y
    
    ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz /opt/
    
    
    RUN tar -xvf /opt/apache-tomcat-8.5.99.tar.gz -C /opt/
    
    COPY context.xml conf/context.xml
    
    EXPOSE 8080
    
    WORKDIR /opt/apache-tomcat-8.5.99
    
    ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war webapps/
    
    CMD sh bin/catalina.sh run
